version: '3.7'

services:

  node_app:
    container_name: node_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - '9090:3000'
    environment:
      - NODE_ENV=development